name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 9.11
        uses: actions/setup-node@v1
        with:
          node-version: 9.11
      - name: npm install, build
        env: # Or as an environment variable
          AWS_KEY: ${{ secrets.AWS_KEY }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
        run: |
          npm install
          npm run build --if-present
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
